name: ipscoringruleenv
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - pytorch=2.3.0
  - torchvision=0.18.1
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - dill=0.3.7
  - requests=2.31.0
  - imbalanced-learn=0.11.0
